### ISSUE TITLE
(Bug) Nothing is being indexed

### ISSUE THREAD

**Issue by banteg** [poanetwork/poa-explorer#41]
the project compiles fine, the database is created, the server is running smoothly, frontend works fine.

i'm using local parity with this config:
```toml
[parity]
chain = "spec.json"

[footprint]
pruning = "archive"
tracing = "on"
```

i tried both master and production branches.

the problem: the database is not populated, nothing is being indexed.

![screen shot 2018-03-06 at 3 50 32 pm](https://user-images.githubusercontent.com/4562643/37022623-1e27bcba-2156-11e8-8edc-f3a0978fb6f5.png)
